version: '3.8'

services:
  # Single Unified Database
  suraksha-db:
    image: mysql:8.0
    container_name: suraksha_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: suraksha_db
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./sql_scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db_data/suraksha:/var/lib/mysql
    restart: unless-stopped